### ISSUE TITLE
Index with name: unique_mdata_key_type already exists with different options

### ISSUE THREAD

**Issue by splatthy** [Hygieia/hygieia-feature-versionone-collector#4]
Greetings,

I'm encountering an issue with the VersionOne collector when I attempt to run it.  Digging through some other issues it sounds like it might be something new after the repo split?  I've tried dropping the index which lets this collector run, but then I get the same error running the API (v3.1.2), and have to drop the index again to get that to run.

--- properties file ---
# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
#dbreplicaset=[false if you are not using MongoDB replicaset]
#dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=############

# Logging File location
logging.file=/opt/hygieia-feature-versionone-collector/target/logs/versionone.log

# PageSize - Expand contract this value depending on VersionOne implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=2000

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000

#############################################################################
# Maximum Kanban iteration length allowed for a sprint start/end date before
# being converted a Kanban generic type iteration.  For example, if you want anything
# longer than a 3-week sprint to be considered as Kanban in the Feature Widget,
# change this value to, for example, 36.  Default value is 28 days.
#
# Note:  This field otherwise does NOT need to be included, and is commented out
#############################################################################
#
# feature.maxKanbanIterationLength=28

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 0/5 * * * *

# VERSIONONE CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
#feature.versionOneProxyUrl=http://proxy.com:9000
feature.versionOneBaseUri=https://www2.v1host.com/
feature.versionOneAccessToken=############

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=v1api-queries
feature.storyQuery=story
feature.projectQuery=projectinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

---- Stack Trace ----
2019-10-31 10:40:21,083 [main] ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metadataRepository': Invocation of init method failed; nested excepti
on is org.springframework.dao.DataIntegrityViolationException: Cannot create index for '' in collection 'metadata' with keys '{ "key" : 1 , "type" : 1}' and
options '{ "name" : "unique_mdata_key_type" , "unique" : true}'. Index already defined as '{ "v" : 2 , "key" : { "key" : 1 , "type" : 1} , "name" : "unique_m
data_key_type" , "ns" : "dashboarddb.metadata"}'.; nested exception is com.mongodb.MongoCommandException: Command failed with error 85: 'Index with name: uni
que_mdata_key_type already exists with different options' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Index with name: unique_m
data_key_type already exists with different options", "code" : 85, "codeName" : "IndexOptionsConflict" }
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578) ~[spring
-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-be
ans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-bean
s-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.R
ELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.5.RE
LEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.REL
EASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEA
SE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:753) ~[spring-beans-
4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839) ~[spring-conte
xt-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) ~[spring-context-4.2.5.RELEASE.jar!/:4
.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1101) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at com.capitalone.dashboard.Application.main(Application.java:21) [versionone-feature-collector.jar!/:3.1.0-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_232]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_232]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_232]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_232]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [versionone-feature-collector.jar!/:3.1.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_232]
Caused by: org.springframework.dao.DataIntegrityViolationException: Cannot create index for '' in collection 'metadata' with keys '{ "key" : 1 , "type" : 1}'
 and options '{ "name" : "unique_mdata_key_type" , "unique" : true}'. Index already defined as '{ "v" : 2 , "key" : { "key" : 1 , "type" : 1} , "name" : "uni
que_mdata_key_type" , "ns" : "dashboarddb.metadata"}'.; nested exception is com.mongodb.MongoCommandException: Command failed with error 85: 'Index with name
: unique_mdata_key_type already exists with different options' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Index with name: uni
que_mdata_key_type already exists with different options", "code" : 85, "codeName" : "IndexOptionsConflict" }
        at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.createIndex(MongoPersistentEntityIndexCreator.java:157) ~[spring-dat
a-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.checkForAndCreateIndexes(MongoPersistentEntityIndexCreator.java:133)
 ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.checkForIndexes(MongoPersistentEntityIndexCreator.java:125) ~[spring
-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.onApplicationEvent(MongoPersistentEntityIndexCreator.java:109) ~[spr
ing-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.onApplicationEvent(MongoPersistentEntityIndexCreator.java:51) ~[spri
ng-data-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163) ~[spring-context-4.
2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136) ~[spring-context-4.
2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381) ~[spring-context-4.2.5.RELEASE.ja
r!/:4.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335) ~[spring-context-4.2.5.RELEASE.ja
r!/:4.2.5.RELEASE]
        at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:326) ~[spring-data-commons-1.11.0.
RELEASE.jar!/:na]
        at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:179) ~[spring-data-commons-1.11.0.
RELEASE.jar!/:na]
        at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:139) ~[spring-data-commons-1.11.0.
RELEASE.jar!/:na]
        at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:66) ~[spring-data-commons-1.11.0.R
ELEASE.jar!/:na]
        at org.springframework.data.mongodb.repository.support.MongoRepositoryFactory.getEntityInformation(MongoRepositoryFactory.java:112) ~[spring-data-mon
godb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.repository.support.MongoRepositoryFactory.getTargetRepository(MongoRepositoryFactory.java:91) ~[spring-data-mongo
db-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:185) ~[spring-data-commons-1
.11.0.RELEASE.jar!/:na]
        at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.initAndReturn(RepositoryFactoryBeanSupport.java:251) ~[spring-data-c
ommons-1.11.0.RELEASE.jar!/:na]
        at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:237) ~[spring-d
ata-commons-1.11.0.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.repository.support.MongoRepositoryFactoryBean.afterPropertiesSet(MongoRepositoryFactoryBean.java:108) ~[spring-da
ta-mongodb-1.8.0.RELEASE.jar!/:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637) ~[spr
ing-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) ~[spring
-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        ... 21 common frames omitted
Caused by: com.mongodb.MongoCommandException: Command failed with error 85: 'Index with name: unique_mdata_key_type already exists with different options' on
 server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Index with name: unique_mdata_key_type already exists with different options", "code"
 : 85, "codeName" : "IndexOptionsConflict" }
        at com.mongodb.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:77) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.CommandProtocol.createCommandResult(CommandProtocol.java:140) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.CommandProtocol.receiveMessage(CommandProtocol.java:131) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:84) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:155) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:219) ~[mongo-java-driver-3.0.2.jar!/:na]

        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:182) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:173) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:145) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:139) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.CreateIndexesOperation$1.call(CreateIndexesOperation.java:116) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.CreateIndexesOperation$1.call(CreateIndexesOperation.java:111) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:186) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:177) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:111) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:66) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.Mongo.execute(Mongo.java:747) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.Mongo$2.execute(Mongo.java:730) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.DBCollection.createIndex(DBCollection.java:1492) ~[mongo-java-driver-3.0.2.jar!/:na]
        at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.createIndex(MongoPersistentEntityIndexCreator.java:142) ~[spring-dat
a-mongodb-1.8.0.RELEASE.jar!/:na]
        ... 41 common frames omitted
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metadataRepository': Invocation of init method failed; nes
ted exception is org.springframework.dao.DataIntegrityViolationException: Cannot create index for '' in collection 'metadata' with keys '{ "key" : 1 , "type"
 : 1}' and options '{ "name" : "unique_mdata_key_type" , "unique" : true}'. Index already defined as '{ "v" : 2 , "key" : { "key" : 1 , "type" : 1} , "name"
: "unique_mdata_key_type" , "ns" : "dashboarddb.metadata"}'.; nested exception is com.mongodb.MongoCommandException: Command failed with error 85: 'Index wit
h name: unique_mdata_key_type already exists with different options' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Index with nam
e: unique_mdata_key_type already exists with different options", "code" : 85, "codeName" : "IndexOptionsConflict" }
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:753)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:295)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1101)
        at com.capitalone.dashboard.Application.main(Application.java:21)
        ... 6 more
Caused by: org.springframework.dao.DataIntegrityViolationException: Cannot create index for '' in collection 'metadata' with keys '{ "key" : 1 , "type" : 1}'
 and options '{ "name" : "unique_mdata_key_type" , "unique" : true}'. Index already defined as '{ "v" : 2 , "key" : { "key" : 1 , "type" : 1} , "name" : "uni
que_mdata_key_type" , "ns" : "dashboarddb.metadata"}'.; nested exception is com.mongodb.MongoCommandException: Command failed with error 85: 'Index with name
: unique_mdata_key_type already exists with different options' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Index with name: uni
que_mdata_key_type already exists with different options", "code" : 85, "codeName" : "IndexOptionsConflict" }
        at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.createIndex(MongoPersistentEntityIndexCreator.java:157)
        at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.checkForAndCreateIndexes(MongoPersistentEntityIndexCreator.java:133)

        at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.checkForIndexes(MongoPersistentEntityIndexCreator.java:125)
        at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.onApplicationEvent(MongoPersistentEntityIndexCreator.java:109)
        at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.onApplicationEvent(MongoPersistentEntityIndexCreator.java:51)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335)
        at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:326)
        at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:179)
        at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:139)
        at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:66)
        at org.springframework.data.mongodb.repository.support.MongoRepositoryFactory.getEntityInformation(MongoRepositoryFactory.java:112)
        at org.springframework.data.mongodb.repository.support.MongoRepositoryFactory.getTargetRepository(MongoRepositoryFactory.java:91)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:185)
        at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.initAndReturn(RepositoryFactoryBeanSupport.java:251)
        at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:237)
        at org.springframework.data.mongodb.repository.support.MongoRepositoryFactoryBean.afterPropertiesSet(MongoRepositoryFactoryBean.java:108)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
        ... 21 more
Caused by: com.mongodb.MongoCommandException: Command failed with error 85: 'Index with name: unique_mdata_key_type already exists with different options' on
 server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Index with name: unique_mdata_key_type already exists with different options", "code"
 : 85, "codeName" : "IndexOptionsConflict" }
        at com.mongodb.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:77)
        at com.mongodb.connection.CommandProtocol.createCommandResult(CommandProtocol.java:140)
        at com.mongodb.connection.CommandProtocol.receiveMessage(CommandProtocol.java:131)
        at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:84)
        at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:155)
        at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:219)
        at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:146)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:182)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:173)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:145)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:139)
        at com.mongodb.operation.CreateIndexesOperation$1.call(CreateIndexesOperation.java:116)
        at com.mongodb.operation.CreateIndexesOperation$1.call(CreateIndexesOperation.java:111)
        at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:186)
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:177)
        at com.mongodb.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:111)
        at com.mongodb.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:66)
        at com.mongodb.Mongo.execute(Mongo.java:747)
        at com.mongodb.Mongo$2.execute(Mongo.java:730)
        at com.mongodb.DBCollection.createIndex(DBCollection.java:1492)
        at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.createIndex(MongoPersistentEntityIndexCreator.java:142)
        ... 41 more

**Comment by rvema** [comment]
I will fix it and let you know

**Comment by rvema** [comment]
@splatthy The fix has been made. Please delete the index from database and run the latest code from master branch and this should fix your issue. Please close this issue once it works for you

**Comment by splatthy** [comment]
Looks good to me now.  I'm getting a different set of errors now, could be related to my configs , going to dig through those to make sure it's not on my end.  This issue should be good to close though.

2019-10-31 22:31:22,361 [main] INFO  com.capitalone.dashboard.Application - Started Application in 7.574 seconds (JVM running for 8.568)                                
2019-10-31 22:32:00,000 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Running Collector: VersionOne                                                           
2019-10-31 22:32:00,011 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Starting Feature collection...                                                   
2019-10-31 22:32:00,014 [taskScheduler-1] INFO  c.c.d.collector.TeamDataClient - Get teams...                                                                           
teaminfo.st 1:36: \n in string                                                                                                                                          
teaminfo.st 2:7: \n in string                                                                                                                                           
teaminfo.st 3:7: \n in string                                                                                                                                           
teaminfo.st 4:13: \n in string                                                                                                                                          
teaminfo.st 5:13: \n in string                                                                                                                                          
teaminfo.st 6:12: \n in string                                                                                                                                          
teaminfo.st 7:7: \n in string                                                                                                                                           
teaminfo.st 8:28: \n in string                                                                                                                                          
2019-10-31 22:32:01,094 [taskScheduler-1] ERROR c.c.d.d.v.VersionOneDataFactoryImpl - There was a problem parsing the JSONArray response value from the source system:  
null | null                                                                                                                                                             
2019-10-31 22:32:01,095 [taskScheduler-1] ERROR c.c.d.collector.FeatureCollectorTask - Error in collecting Version One Data: [-1] FAILED: FAILED: VersionOne response in
cluded unexpected JSON format

**Comment by rvema** [comment]
@splatthy For this error, I am not sure about the reason. You may create another issue so that someone else from the community may be able to look into the same.

**Comment by splatthy** [comment]
Thanks I think I tracked it down. 

If anyone stumbles on this looking for a lead, I added a logger to return the string that was trying to be converted and it turns out it was a response page due to an IP restriction in our V1 host. 

If I run into anything else after sorting that out I’ll create a new issue. Thanks.
